[pytest]
DJANGO_SETTINGS_MODULE = my_new_project.settings
pythonpath =
    .
    my_new_project
testpaths = my_new_project/res_backend/tests
django_find_project = false
markers =
    integration: hits live endpoints using BASE_URL
