-- User History Migration for Itinerary Generation
-- Run this in your Supabase SQL Editor

-- Table to store user's itinerary history
CREATE TABLE IF NOT EXISTS user_itinerary_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  itinerary_id TEXT,
  place_ids TEXT[],
  generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  filters JSONB,
  CONSTRAINT idx_user_history UNIQUE(user_id, itinerary_id)
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_user_history_user ON user_itinerary_history(user_id);
CREATE INDEX IF NOT EXISTS idx_user_history_generated ON user_itinerary_history(generated_at DESC);

-- Table to track user interactions with venues
CREATE TABLE IF NOT EXISTS user_venue_interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  place_id TEXT NOT NULL,
  interaction_type TEXT CHECK (interaction_type IN ('seen', 'not_interested', 'loved')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT unique_user_venue UNIQUE(user_id, place_id, interaction_type)
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_venue_interactions_user ON user_venue_interactions(user_id);
CREATE INDEX IF NOT EXISTS idx_venue_interactions_place ON user_venue_interactions(place_id);

-- Enable Row Level Security (optional but recommended)
ALTER TABLE user_itinerary_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_venue_interactions ENABLE ROW LEVEL SECURITY;

-- Create policies for read/write access
CREATE POLICY "Enable read access for all users" ON user_itinerary_history FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON user_itinerary_history FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable read access for all users" ON user_venue_interactions FOR SELECT USING (true);
CREATE POLICY "Enable insert/update access for all users" ON user_venue_interactions FOR ALL USING (true);

-- Table to store user-saved itineraries (only those explicitly saved by users)
CREATE TABLE IF NOT EXISTS user_saved_itineraries (
  id TEXT PRIMARY KEY,  -- This will be the UUID from generate_itinerary
  user_id TEXT NOT NULL,
  places JSONB,  -- Store the full itinerary data
  saved_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  filters JSONB,  -- Store the original filters used
  narrative TEXT,
  total_walk_time_mins INTEGER
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_saved_itineraries_user ON user_saved_itineraries(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_itineraries_saved ON user_saved_itineraries(saved_at DESC);

-- Enable Row Level Security
ALTER TABLE user_saved_itineraries ENABLE ROW LEVEL SECURITY;

-- Create policies for read/write access
CREATE POLICY "Enable read access for all users" ON user_saved_itineraries FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON user_saved_itineraries FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON user_saved_itineraries FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON user_saved_itineraries FOR DELETE USING (true);
