-- Add reviews table to Supabase
-- Run this in your Supabase SQL Editor

-- 1. Create the reviews table
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id TEXT REFERENCES venues(place_id) ON DELETE CASCADE,
  author TEXT,
  rating INT,
  text TEXT,
  text_length INT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Prevent duplicate reviews (same author + text = duplicate)
  UNIQUE(place_id, author, text)
);

-- 2. Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_reviews_place_id ON reviews(place_id);
CREATE INDEX IF NOT EXISTS idx_reviews_rating ON reviews(rating);

-- 3. Add a review_count column to venues (optional but useful)
ALTER TABLE venues ADD COLUMN IF NOT EXISTS scraped_review_count INT DEFAULT 0;

-- 4. Create a function to update review count (optional)
CREATE OR REPLACE FUNCTION update_venue_review_count()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE venues
  SET scraped_review_count = (
    SELECT COUNT(*) FROM reviews WHERE place_id = NEW.place_id
  )
  WHERE place_id = NEW.place_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 5. Create trigger to auto-update review count (optional)
DROP TRIGGER IF EXISTS trigger_update_review_count ON reviews;
CREATE TRIGGER trigger_update_review_count
AFTER INSERT OR DELETE ON reviews
FOR EACH ROW
EXECUTE FUNCTION update_venue_review_count();
