# Generated by Django 5.1.6 on 2025-05-08 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('price_range', models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$'), ('$$$$', '$$$$')], max_length=4)),
                ('dining_style', models.CharField(choices=[('FAST_FOOD', 'Fast Food'), ('CAFE', 'Café'), ('CASUAL', 'Casual Dining'), ('FINE', 'Fine Dining'), ('BUFFET', 'Buffet'), ('FOOD_TRUCK', 'Food Truck')], max_length=20)),
                ('location_region', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('VEGAN', 'Vegan-friendly'), ('FAMILY', 'Family-friendly'), ('OUTDOOR', 'Outdoor Seating'), ('PET', 'Pet-friendly'), ('DELIVERY', 'Delivery'), ('HALAL', 'Halal'), ('LATE', 'Open Late'), ('TAKEOUT', 'Takeout')], max_length=20)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='res_backend.establishment')),
            ],
            options={
                'unique_together': {('establishment', 'feature_type')},
            },
        ),
    ]
