# Generated by Django 5.1.6 on 2025-05-08 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('VIEW', 'Viewed'), ('SAVE', 'Saved to favorites'), ('VISIT', 'Visited'), ('RATE', 'Rated')], max_length=10)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('trip_id', models.CharField(blank=True, help_text='ID of the associated trip', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='res_backend.establishment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
