# Generated by Django 5.2.8 on 2025-12-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_backend', '0004_publicitinerary_userstats_itinerarylike_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCreatedItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('price_range', models.CharField(blank=True, max_length=50)),
                ('min_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_km', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('itinerary_data', models.JSONField(help_text='Full itinerary with restaurants and enrichment data')),
                ('total_restaurants', models.IntegerField(default=0)),
                ('enriched_count', models.IntegerField(default=0)),
                ('enrichment_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on home page')),
                ('sample_image_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['cuisine', 'price_range', 'is_featured'], name='res_backend_cuisine_7573a8_idx'), models.Index(fields=['latitude', 'longitude'], name='res_backend_latitud_b04730_idx')],
            },
        ),
    ]
