-- Create the table for Hidden Gems
CREATE TABLE IF NOT EXISTS public.hidden_gems (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  place_id TEXT NOT NULL,
  name TEXT,
  address TEXT,
  street_address TEXT,
  city TEXT,
  state TEXT,
  zip TEXT,
  latitude FLOAT,
  longitude FLOAT,
  rating FLOAT,
  review_count INT,
  phone TEXT,
  website TEXT,
  hours JSONB,
  photos JSONB,
  vibe_slug TEXT,
  vibe_group TEXT,
  neighborhood TEXT,
  region TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Prevent duplicates for the same place in the same vibe/neighborhood
  UNIQUE(place_id, vibe_slug, neighborhood)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_hidden_gems_vibe ON public.hidden_gems(vibe_slug);
CREATE INDEX IF NOT EXISTS idx_hidden_gems_region ON public.hidden_gems(region);
CREATE INDEX IF NOT EXISTS idx_hidden_gems_neighborhood ON public.hidden_gems(neighborhood);

-- Enable Row Level Security (RLS)
ALTER TABLE public.hidden_gems ENABLE ROW LEVEL SECURITY;

-- Create policy for read access
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'hidden_gems' AND policyname = 'Public hidden gems are viewable by everyone.'
    ) THEN
        CREATE POLICY "Public hidden gems are viewable by everyone."
          ON public.hidden_gems FOR SELECT
          USING ( true );
    END IF;
END
$$;
