# Generated by Django 5.1.6 on 2025-12-03 20:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res_backend', '0003_establishment_latitude_establishment_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firestore_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('user_id', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user_photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('neighborhood', models.CharField(max_length=200)),
                ('categories', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('added_to_schedule_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, unique=True)),
                ('total_public_itineraries', models.IntegerField(default=0)),
                ('total_likes_received', models.IntegerField(default=0)),
                ('profile_photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_likes_received'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itinerary_firestore_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-liked_at'],
                'unique_together': {('itinerary_firestore_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='ScrapedRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('yelp', 'Yelp'), ('google', 'Google Maps'), ('tripadvisor', 'TripAdvisor'), ('foursquare', 'Foursquare'), ('opentable', 'OpenTable'), ('other', 'Other')], db_index=True, max_length=50)),
                ('source_id', models.CharField(help_text='Original ID from source platform', max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(db_index=True, default='USA', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('price_range', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hours', models.JSONField(blank=True, default=dict)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('menu_items', models.JSONField(blank=True, default=list)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Store original scraped data for reference')),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified restaurant')),
                ('is_active', models.BooleanField(default=True, help_text='Restaurant is still open')),
                ('data_quality_score', models.IntegerField(default=0, help_text='Data completeness score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('scraped_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('duplicate_of', models.ForeignKey(blank=True, help_text='If this is a duplicate, link to the canonical restaurant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='res_backend.scrapedrestaurant')),
            ],
            options={
                'verbose_name': 'Scraped Restaurant',
                'verbose_name_plural': 'Scraped Restaurants',
                'ordering': ['-data_quality_score', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantDeduplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='Similarity score (0-1)')),
                ('is_duplicate', models.BooleanField(blank=True, help_text='Manual verification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_duplicates', to='res_backend.scrapedrestaurant')),
                ('restaurant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dup_as_restaurant1', to='res_backend.scrapedrestaurant')),
                ('restaurant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dup_as_restaurant2', to='res_backend.scrapedrestaurant')),
            ],
            options={
                'ordering': ['-similarity_score'],
            },
        ),
        migrations.AddIndex(
            model_name='scrapedrestaurant',
            index=models.Index(fields=['latitude', 'longitude'], name='restaurant_location_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedrestaurant',
            index=models.Index(fields=['city', 'state'], name='restaurant_city_state_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedrestaurant',
            index=models.Index(fields=['rating'], name='restaurant_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedrestaurant',
            index=models.Index(fields=['source', 'is_active'], name='restaurant_source_active_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedrestaurant',
            index=models.Index(fields=['data_quality_score', 'is_verified'], name='restaurant_quality_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedrestaurant',
            index=models.Index(fields=['name'], name='restaurant_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scrapedrestaurant',
            unique_together={('source', 'source_id')},
        ),
        migrations.AlterUniqueTogether(
            name='restaurantdeduplication',
            unique_together={('restaurant1', 'restaurant2')},
        ),
    ]
